[package]
name = "dir-tree-cli"
version = "0.1.0"
edition = "2021"
authors = ["Aurimar Lopes"]
license = "MIT"
exclude = [".github/*"]

[dependencies]
clap = "4.5.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "dtc"
path = "src/main.rs"
